services:
  app:
    build: .
    restart: always
    tty: true
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:poke-chatbot-project@postgres:5432/poke-chatbot-project

  postgres:
    image: postgres:17-alpine3.21
    restart: always
    ports:
      - "5432:5432"
    environment:
     POSTGRES_PASSWORD: poke-chatbot-project
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data: